name: Deploy to Vercel

on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Install Vercel CLI
      run: npm install vercel -g

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_AUTH_TOKEN }}
      env:
        CI: false
        VERCEL_AUTH_TOKEN: ${{ secrets.VERCEL_AUTH_TOKEN }}
