name: Deploy to Netlify

on:
  push:
    branches:
      - feature/wallet-integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Install Netlify CLI
      run: npm install netlify-cli -g

    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=out --message "GitHub Actions deploy" --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
      env:
        CI: false
